"""Expected A-Box content, copied from the pkmn A-Box completion spec and the pkmn A-Box note.

Class names carry their prefix (`pkmn:` or `mo:`); individuals are named by their ttl local name.
"""

CLASS_COUNTS: dict[str, int] = {
    "mo:Universe": 1,
    "pkmn:Type": 18,
    "pkmn:Stat": 6,
    "pkmn:BattleStat": 3,
    "pkmn:MoveDamageClass": 3,
    "pkmn:EggGroup": 15,
    "pkmn:Nature": 25,
    "pkmn:StatusCondition": 8,
    "pkmn:VolatileCondition": 20,
    "pkmn:Weather": 9,
    "pkmn:Terrain": 4,
    "pkmn:EntryHazard": 5,
    "pkmn:FieldEffect": 10,
    "pkmn:MoveFlag": 19,
    "pkmn:Generation": 9,
    "mo:Region": 11,
    "pkmn:GenerationMechanic": 5,
}

VOCABULARY_LABELS: dict[str, tuple[str, ...]] = {
    "pkmn:EggGroup": (
        "Monster",
        "Water 1",
        "Water 2",
        "Water 3",
        "Bug",
        "Flying",
        "Field",
        "Fairy",
        "Grass",
        "Human-Like",
        "Mineral",
        "Amorphous",
        "Ditto",
        "Dragon",
        "No Eggs Discovered",
    ),
    "pkmn:StatusCondition": (
        "Burn",
        "Freeze",
        "Paralysis",
        "Poison",
        "Badly Poisoned",
        "Sleep",
        "Frostbite",
        "Drowsy",
    ),
    "pkmn:VolatileCondition": (
        "Confused",
        "Flinch",
        "Infatuated",
        "Taunted",
        "Encore",
        "Move Disabled",
        "Unable to Repeat",
        "Healing Prevented",
        "Leech Seeded",
        "Drowsy",
        "Can't Escape",
        "Bound",
        "No Ability",
        "Substitute",
        "Telekinesis",
        "Magnet Rise",
        "Concealed",
        "Sky-High",
        "Submerged",
        "Underground",
    ),
    "pkmn:EntryHazard": ("Spikes", "Stealth Rock", "Toxic Spikes", "Sticky Web", "Steelsurge"),
    "pkmn:FieldEffect": (
        "Trick Room",
        "Gravity",
        "Magic Room",
        "Wonder Room",
        "Tailwind",
        "Light Screen",
        "Reflect",
        "Aurora Veil",
        "Safeguard",
        "Mist",
    ),
}

ALIASES: dict[str, tuple[str, ...]] = {
    "stealthRock": ("Pointed Stones",),
    "toxicSpikes": ("Poison Spikes",),
    "steelsurge": ("G-Max Steelsurge", "Sharp Steel"),
    "confused": ("Confusion",),
    "infatuated": ("Infatuation",),
    "taunted": ("Taunt",),
    "moveDisabled": ("Disable",),
    "unableToRepeat": ("Torment",),
    "healingPrevented": ("Heal Block",),
    "leechSeeded": ("Leech Seed",),
    "volatileDrowsy": ("Yawn",),
    "cantEscape": ("Trapped",),
}

REMOVED_LOCAL_NAMES: tuple[str, ...] = (
    "curse",
    "nightmare",
    "aquaRing",
    "ingrain",
    "embargo",
    "semiInvulnerable",
    "trapped",
    "yawn",
    "disable",
    "torment",
    "healBlock",
    "taunt",
    "confusion",
    "infatuation",
    "leechSeed",
)
