"""Expected A-Box content, copied from the pkmn A-Box completion spec and the pkmn A-Box note.

Class names carry their prefix (`pkmn:` or `mo:`); individuals are named by their ttl local name.
"""

CLASS_COUNTS: dict[str, int] = {
    "mo:Universe": 1,
    "pkmn:Type": 18,
    "pkmn:Stat": 6,
    "pkmn:BattleStat": 3,
    "pkmn:MoveDamageClass": 3,
    "pkmn:EggGroup": 15,
    "pkmn:Nature": 25,
    "pkmn:StatusCondition": 8,
    "pkmn:VolatileCondition": 20,
    "pkmn:Weather": 9,
    "pkmn:Terrain": 4,
    "pkmn:EntryHazard": 5,
    "pkmn:FieldEffect": 10,
    "pkmn:MoveFlag": 19,
    "pkmn:Generation": 9,
    "mo:Region": 11,
    "pkmn:GenerationMechanic": 5,
    "pkmn:VersionGroup": 24,
    "pkmn:Version": 40,
}

VOCABULARY_LABELS: dict[str, tuple[str, ...]] = {
    "pkmn:EggGroup": (
        "Monster",
        "Water 1",
        "Water 2",
        "Water 3",
        "Bug",
        "Flying",
        "Field",
        "Fairy",
        "Grass",
        "Human-Like",
        "Mineral",
        "Amorphous",
        "Ditto",
        "Dragon",
        "No Eggs Discovered",
    ),
    "pkmn:StatusCondition": (
        "Burn",
        "Freeze",
        "Paralysis",
        "Poison",
        "Badly Poisoned",
        "Sleep",
        "Frostbite",
        "Drowsy",
    ),
    "pkmn:VolatileCondition": (
        "Confused",
        "Flinch",
        "Infatuated",
        "Taunted",
        "Encore",
        "Move Disabled",
        "Unable to Repeat",
        "Healing Prevented",
        "Leech Seeded",
        "Drowsy",
        "Can't Escape",
        "Bound",
        "No Ability",
        "Substitute",
        "Telekinesis",
        "Magnet Rise",
        "Concealed",
        "Sky-High",
        "Submerged",
        "Underground",
    ),
    "pkmn:EntryHazard": ("Spikes", "Stealth Rock", "Toxic Spikes", "Sticky Web", "Steelsurge"),
    "pkmn:FieldEffect": (
        "Trick Room",
        "Gravity",
        "Magic Room",
        "Wonder Room",
        "Tailwind",
        "Light Screen",
        "Reflect",
        "Aurora Veil",
        "Safeguard",
        "Mist",
    ),
}

ALIASES: dict[str, tuple[str, ...]] = {
    "stealthRock": ("Pointed Stones",),
    "toxicSpikes": ("Poison Spikes",),
    "steelsurge": ("G-Max Steelsurge", "Sharp Steel"),
    "confused": ("Confusion",),
    "infatuated": ("Infatuation",),
    "taunted": ("Taunt",),
    "moveDisabled": ("Disable",),
    "unableToRepeat": ("Torment",),
    "healingPrevented": ("Heal Block",),
    "leechSeeded": ("Leech Seed",),
    "volatileDrowsy": ("Yawn",),
    "cantEscape": ("Trapped",),
}

REMOVED_LOCAL_NAMES: tuple[str, ...] = (
    "curse",
    "nightmare",
    "aquaRing",
    "ingrain",
    "embargo",
    "semiInvulnerable",
    "trapped",
    "yawn",
    "disable",
    "torment",
    "healBlock",
    "taunt",
    "confusion",
    "infatuation",
    "leechSeed",
)

# (group label, expected group id, generation local name, version labels)
GAME_GROUPS: tuple[tuple[str, str, str, tuple[str, ...]], ...] = (
    ("Red-Blue", "red-blue", "gen1", ("Red", "Blue")),
    ("Yellow", "yellow", "gen1", ("Yellow",)),
    ("Gold-Silver", "gold-silver", "gen2", ("Gold", "Silver")),
    ("Crystal", "crystal", "gen2", ("Crystal",)),
    ("Ruby-Sapphire", "ruby-sapphire", "gen3", ("Ruby", "Sapphire")),
    ("Emerald", "emerald", "gen3", ("Emerald",)),
    ("FireRed-LeafGreen", "firered-leafgreen", "gen3", ("FireRed", "LeafGreen")),
    ("Colosseum", "colosseum", "gen3", ("Colosseum",)),
    ("XD", "xd", "gen3", ("XD",)),
    ("Diamond-Pearl", "diamond-pearl", "gen4", ("Diamond", "Pearl")),
    ("Platinum", "platinum", "gen4", ("Platinum",)),
    ("HeartGold-SoulSilver", "heartgold-soulsilver", "gen4", ("HeartGold", "SoulSilver")),
    ("Black-White", "black-white", "gen5", ("Black", "White")),
    ("Black 2-White 2", "black-2-white-2", "gen5", ("Black 2", "White 2")),
    ("X-Y", "x-y", "gen6", ("X", "Y")),
    (
        "Omega Ruby-Alpha Sapphire",
        "omega-ruby-alpha-sapphire",
        "gen6",
        ("Omega Ruby", "Alpha Sapphire"),
    ),
    ("Sun-Moon", "sun-moon", "gen7", ("Sun", "Moon")),
    ("Ultra Sun-Ultra Moon", "ultra-sun-ultra-moon", "gen7", ("Ultra Sun", "Ultra Moon")),
    (
        "Let's Go Pikachu-Let's Go Eevee",
        "lets-go-pikachu-lets-go-eevee",
        "gen7",
        ("Let's Go Pikachu", "Let's Go Eevee"),
    ),
    ("Sword-Shield", "sword-shield", "gen8", ("Sword", "Shield")),
    (
        "Brilliant Diamond and Shining Pearl",
        "brilliant-diamond-and-shining-pearl",
        "gen8",
        ("Brilliant Diamond", "Shining Pearl"),
    ),
    ("Legends: Arceus", "legends-arceus", "gen8", ("Legends: Arceus",)),
    ("Scarlet-Violet", "scarlet-violet", "gen9", ("Scarlet", "Violet")),
    ("Legends: Z-A", "legends-z-a", "gen9", ("Legends: Z-A",)),
)

VERSION_IDS_SPOT_CHECK: tuple[str, ...] = (
    "lets-go-pikachu",
    "lets-go-eevee",
    "firered",
    "heartgold",
    "black-2",
    "omega-ruby",
    "legends-z-a",
)

ABSENT_GAME_LABELS: tuple[str, ...] = (
    "Green",
    "Stadium",
    "Isle of Armor",
    "Crown Tundra",
    "Teal Mask",
    "Indigo Disk",
    "Mega Dimension",
    "Winds and Waves",
)
